version: '3'
services:
  db:
    image: "postgres:10.5-alpine"
    ports:
      - "15432:5432"
    volumes:
      - "comix-data:/var/lib/postgresql"
    environment:
      POSTGRES_DB:       marvel
      POSTGRES_USER:     iron_patriot
      POSTGRES_PASSWORD: WARMACHINEROX
      #based on https://www.youtube.com/watch?v=S0tFKasw2RA
  pgadmin:
    image: dpage/pgadmin4
    ports: ["18080:80"]
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"

volumes:
  comix-data:
  pgadmin-data:

