name:                hasComix
version:             0.1.0.0
github:              "epsilonhalbe/hasComix"
license:             BSD3
author:              "Martin Heuschober"
maintainer:          "epsilonhalbe@gmail.com"
copyright:           "2018 Martin Heuschober"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hasComix#readme>

dependencies:
- base >= 4.7 && < 5
- cassava

ghc-options:
- -Wall

library:
  exposed-modules:
  - Comix.Lib
  - Comix.Data
  - Comix.Data.Rating

  - Data.Time.Orphans
  source-dirs: src
  dependencies:
  - bytestring
  - persistent
  - persistent-template
  - text
  - time

executables:
  hasComix:
    main:                Main.hs
    source-dirs:         app
    other-modules:
    - Command
    - Command.Capitalize
    - Command.Migrate
    - Command.Smallify
    - Command.ImportCsv
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasComix
    - bytestring
    - conduit
    - conduit-extra
    - configurator
    - directory
    - extra
    - filepath
    - monad-logger
    - optparse-applicative
    - persistent
    - persistent-postgresql
    - resourcet
    - vector
    - text

tests:
  hasComix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasComix
    - bytestring
    - hspec
    - hspec-expectations-pretty-diff
    - time
    - text
